version: "3"
services:
  go:
    build: ./go
    depends_on:
    - db
    volumes:
      - ./:/go/src/app
    tty: true

  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
    # image: mysql:5.7
    # environment:
    # - MYSQL_DATABASE=test_db
    # - MYSQL_ROOT_PASSWORD=password
    # command: >
    #   --character-set-server=utf8mb4
    #   --collation-server=utf8mb4_general_ci
    #   --innodb_file_per_table
    #   --innodb_file_format=BARRACUDA
    #   --innodb_large_prefix=1
    # ports:
    #   - 3306:3306
